name: main file

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps: 
      - name: create string
        run: |
          MY_STRING= ${{ github.event.inputs.stringname }}'
          echo "::set-output name=content::$MY_STRING"
