- name: Send some mail
  uses: wadeww/send-email-action@master
  with:
    server_address: smtp.gmail.com
    port: 465
    username: shivranjani.b@gmail.com
    password: Miracleinlife@27
    subject: Workflow finished
    body: Job completed ${{job.status}}
    to: shivranjaniaws@gmail.com
    from: Me
