- name: Send some mail
  uses: wadeww/send-email-action@master
  with:
    server_address: smtp.gmail.com
    port: 465
    username: ${{secrets.MAIL_ADDRESS}}
    password: ${{secrets.MAIL_PASSWORD}}
    subject: Workflow finished
    body: Job completed ${{job.status}}
    to: shivranjaniaws@gmail.com
    from: Me
